### ISSUE TITLE
How to find meter number?

### ISSUE THREAD

**Issue by liviooo** [tijsverkoyen/HomeAssistant-EnergyID#13]
I try to set my Tesla mileage on a daily basis in EnergyID via an automation. But having troubles finding the correct EnergyID meter number for this meter. I use the meter number from the EnergyID url for that specific meter, but this doesn't work. Any idea?

````yaml
service: energy_id.set_meter_reading
data:
  device_id: 97c1470-1a60-4462-b270-42841143cf1a2
  value: '{{ (states(''sensor.tesla_odometer'') | float) }}'
  date: '{{ (now() - timedelta(hours=2)).strftime(''%Y-%m-%d %H:%M'') }}'
enabled: true
````

Error: Stopped because an error was encountered at October 4, 2023, 20:24:52 (runtime: 0.02 seconds)
Meter not found
